version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./.var/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

