# Generated by Django 3.2.22 on 2023-10-29 20:21

import applications.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateField(validators=[applications.products.models.validate_date]),
        ),
    ]
