# Generated by Django 3.2.22 on 2023-10-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerships_supplier', to='factory.factory'),
        ),
    ]
