# Generated by Django 3.2.22 on 2023-10-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('dealership', '0002_alter_dealership_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerships_contacts', to='contacts.contacts'),
        ),
    ]
